[environments]
  [environments.development]
    name = "locations"
    namespace = "draftdev"
    wait = false
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = "Dockerfile"
    chart = "charts"
